### ISSUE TITLE
Make CircleCI tests cache

### ISSUE THREAD

**Issue by ckcollab** [codalab/competitions-v2#146] opened 2019-02-28 20:03 UTC
- [ ] Cache pip installs
- [ ] Cache nvm install
- [ ] Cache docker stuff ???

**Comment by jimmykodes** [comment] 2019-11-05 19:43
duplicate of:
https://github.com/codalab/competitions-v2/issues/219
keeping the more detailed issue.

**Closed by jimmykodes** 2019-11-05 19:43 UTC
