### ISSUE TITLE
Implement competition participation features

### ISSUE THREAD

**Issue by ckcollab** [codalab/competitions-v2#118] opened 2019-01-28 22:53 UTC
- [ ] Approve some kind of Terms of Service (this would be optional, only some competitions would require it -- could be a field underneath competition description?)

- [ ] Some kind of participant management screen (see v1.5)
- [ ] Approve/deny entry into competition (on above screen) -- should be able to give a reason
- [ ] On the participant management screen, make room for a button to "email all participants" and another button to "email specific participant"

Can see how v1.5 works to get an idea -- can go over this on screenshare when ready

**Comment by jimmykodes** [comment] 2019-11-05 21:08
duplicate of https://github.com/codalab/competitions-v2/issues/134

**Closed by jimmykodes** 2019-11-05 21:08 UTC
