### ISSUE TITLE
Bundle uploading/unpacking taking forever

### ISSUE THREAD

**Issue by Didayolo** [codalab/competitions-v2#273] opened 2019-11-26 18:28 UTC
I'm trying to upload the following bundle to Codalab V2 (prod LRI instance):

[Mortality challenge bundle.](https://drive.google.com/open?id=1fPiNkU-tn-2awkPGWsADY4yuV63QZLSU)

The uploading seems to work but then the **unpacking** step never finishes.

**Comment by Didayolo** [comment] 2019-11-28 13:19
Update: I tried to upload the bundle on Codalab V1.5 (codalab.org) and it is working well.

**Comment by ckcollab** [comment] 2019-12-03 11:56
It looks like the problem was due to this line in the yaml:

```yaml
# remove me to fix bundle unpacking
competition_docker_image: ''
```

Was this generated by v1.5 dumps?

Pushing some code in a new branch that makes this error clearer

**Comment by Didayolo** [comment] 2019-12-03 12:37
Thank you for your answer.

Bundle are not supposed to be backward compatible? 

If no, we should have a script converting from V1.5 yaml to V2 yaml file.

**Comment by ckcollab** [comment] 2019-12-03 12:49
> If no, we should have a script converting from V1.5 yaml to V2 yaml file.

This happens transparently if you upload a v1.5 bundle.

Was this bundle generated by v1.5 dumps? Trying to understand where the blank argument came from.

**Comment by Didayolo** [comment] 2019-12-03 12:49
It worked!

Now I still have another not working bundle. I corrected the `competition_docker_image` line in the yaml file too but it is not sufficient. There are still no error message when the unpacking takes forever (maybe you didn't push the new change yet).

This one is a competition with 2 tasks (therefore 2 scores). Maybe this is linked to the issue.

Here is the bundle:

[Chems bundle.](https://drive.google.com/open?id=1BMWrbSkee7gmCYRvZjzMle61Pf9ZIKrq)

**Comment by Didayolo** [comment] 2019-12-03 12:52
> Was this bundle generated by v1.5 dumps? Trying to understand where the blank argument came from

I am not sure. I wrote this yaml file by hand from another example. Maybe the previous example had this argument and I just removed the content inside the quotation mark. Or maybe I took it from a dump and made changes.

**Comment by ckcollab** [comment] 2019-12-03 12:59
Got it, since it works on V1.5 we'll make empty arguments work on v2

**Comment by Didayolo** [comment] 2019-12-03 13:12
OK that's perfect.

For the "Chems challenge bundle", the error comes from something else.

**Comment by Didayolo** [comment] 2019-12-17 09:49
Still not able to upload the [Chems challenge bundle](https://drive.google.com/file/d/1BMWrbSkee7gmCYRvZjzMle61Pf9ZIKrq/view).

**Comment by Didayolo** [comment] 2019-12-18 13:21
I've just tried another bundle that works on Codalab V1 but fails on Codalab V2.

Also, I had a bundle failing in both versions but in Codalab V1 I had an error message while in Codalab V2 I just have this infinitely long unpacking.

**Comment by jimmykodes** [comment] 2019-12-18 16:18
I will look at implementing a fix for the fact that you aren't getting an error message for this bundle. The error I have found is that the `get_starting_kit.html` is an empty file, and pages with no content are not considered valid. So if you add some text (or remove the file altogether) the competition should upload correctly. (I have confirmed that removing the file from the yaml will successfully upload on my local v2 instance)

**Comment by Didayolo** [comment] 2019-12-18 16:23
Thank you very much for your help. I'll try this as soon as possible.

As for the previous error in this thread (the empty field in yaml file), empty HTML pages didn't cause the bundle to fail in Codalab V1.

For convenience and back compatibility, maybe empty HTML files should be handled.

> I will look at implementing a fix for the fact that you aren't getting an error message for this bundle.

Indeed, error message are crucial for debugging bundles.

**Comment by jimmykodes** [comment] 2019-12-18 18:35
This should be fixed on the server now. 
We have allowed for empty HTML files for compatibility convenience.

**Comment by Didayolo** [comment] 2019-12-19 06:10
Indeed it works, thank you very much. I can now upload the Chems bundle.

The last one is [Heart Attack challenge bundle](https://drive.google.com/open?id=1uaTrlVMHBCmALVLJEopHSDJW__B9Oocm).

As always, the unpacking doesn't finish so I don't have an error message. This competition should be very close to "Chems" so I don't see why it isn't working.

**Comment by jimmykodes** [comment] 2019-12-19 06:31
This is because your `competition.yaml` has a space as the first character of your file, which the yams format reads as an invalid start of file, and bombs out. Removing that space should fix the upload.

While i do not believe it is possible to engineer a solution that will be able to report _all_ of these kinds of edge case bugs to users, I have some ideas I can discuss with Eric to at least prevent the "hanging" of the unpacking step. Even if the best error we can give is, "Something appears to be wrong with your bundle", I think that will be a better solution than just letting it "unpack" indefinitely.

**Comment by Didayolo** [comment] 2019-12-19 06:52
Hi Jimmy,

I can't see any space at the beginning of the file:

![yaml](https://user-images.githubusercontent.com/11784999/71151582-5f419a00-2234-11ea-8c90-684d6135b492.png)

Moreover, this bundle works in Codalab V1 so the YAML file should be readable.

**Comment by jimmykodes** [comment] 2019-12-19 07:14
Ah. My mistake, not sure how I must have added that space at the begging of the file...

I do not have credentials to log in to the production server to look at logs there so I am limited in my debugging until tomorrow when I can talk w/ eric, however. If I were to guess, can you try removing the blank competition docker image line?

 I know this was an issue that was fixed in an earlier commit, but it is possible that was reverted by our most recent patch, fixing blank page content. If this does work, I should be able to have this fixed for real early tomorrow.

**Closed** 2019-12-19 07:45 UTC
Labels: bug

**Comment by Didayolo** [comment] 2019-12-19 09:36
Awesome, everything works now. Thank you for your efficiency!
